Repository MohamedNiaissa/ProjetBackEnd, pull requests merged in 2022-10, with the labels that each got.

#6 New structure to work with sh, init mongodb and check for validity before launching server
  .gitignore
  backend/app/__init__.py
  backend/app/api/__init__.py
  backend/app/api/deps.py
  backend/app/api/v1/__init__.py
  backend/app/api/v1/api.py
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/likes.py
  backend/app/api/v1/endpoints/posts.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
  backend/app/core/__init__.py
  backend/app/core/config.py
  backend/app/core/dotenv.py
  backend/app/core/security.py
  backend/app/crud/__init__.py
  backend/app/crud/crud_comments.py
  backend/app/crud/crud_likes.py
  backend/app/crud/crud_posts.py
  backend/app/crud/crud_reports.py
  backend/app/crud/crud_users.py
  backend/app/main.py
  backend/app/mongo/__init__.py
  backend/app/mongo/init_db.py
  backend/app/mongo/models/__init__.py
  backend/app/mongo/models/comments.py
  backend/app/mongo/models/likes.py
  backend/app/mongo/models/posts.py
  backend/app/mongo/models/reports.py
  backend/app/mongo/models/users.py
  backend/app/mongo/schemas/__init__.py
  backend/app/mongo/schemas/comments.py
  backend/app/mongo/schemas/likes.py
  backend/app/mongo/schemas/posts.py
  backend/app/mongo/schemas/reports.py
  backend/app/mongo/schemas/users.py
  backend/app/utils.py
  backend/app/uvicorn_pre_start.py
  backend/prestart.sh
  history.md
  main.py
Labels: setup

#17 Setup/rooters name of the function camelCase to snake_case
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/likes.py
  backend/app/api/v1/endpoints/posts.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
Labels: setup

#36 new template for CRUD users and docstring added
  backend/app/api/v1/endpoints/users.py
  backend/app/crud/crud_users.py
  history.md
Labels: dev, CRUD

#37 Jwt encode/decode + database dependence
  backend/app/api/deps.py
  backend/app/api/v1/endpoints/__init__.py
  backend/app/core/config.py
  backend/app/core/security.py
  backend/app/mongo/init_db.py
  backend/app/uvicorn_pre_start.py
  history.md
  requirements.txt
Labels: dev

#38 Models/reports
  backend/app/mongo/models/reports.py
  history.md
Labels: documentation, dev

#39 Models/likes
  backend/app/mongo/models/likes.py
  history.md
Labels: documentation, dev

#43 close #23, new template for CRUD comments and docstring added
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/likes.py
  backend/app/api/v1/endpoints/posts.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
  backend/app/crud/crud_comments.py
  backend/app/crud/crud_likes.py
  backend/app/crud/crud_posts.py
  backend/app/crud/crud_reports.py
  backend/app/crud/crud_users.py
  history.md
Labels: dev, CRUD

#40 close #26, new template for CRUD reports and docstring added
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
  backend/app/crud/crud_reports.py
  backend/app/crud/crud_users.py
  history.md
Labels: dev, CRUD

#44 Schemas/user
  backend/app/mongo/schemas/users.py
  history.md
Labels: documentation, dev

#46 Schemas/likes
  authors.md
  backend/app/mongo/schemas/likes.py
  history.md
Labels: documentation, dev

#47 Auth/decorator auth guard
  backend/app/api/deps.py
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/likes.py
  backend/app/api/v1/endpoints/posts.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
  history.md
  readme.md
Labels: dev

#51 Fix/crud
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/likes.py
  backend/app/api/v1/endpoints/posts.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
  backend/app/crud/crud_users.py
  history.md
Labels: bug, dev, CRUD

#50 Schemas/posts history 0.2.19
  backend/app/mongo/schemas/posts.py
  history.md
Labels: documentation, dev

#52 Added db collections to each crud
  backend/app/crud/crud_comments.py
  backend/app/crud/crud_likes.py
  backend/app/crud/crud_posts.py
  backend/app/crud/crud_reports.py
  backend/app/crud/crud_users.py
  history.md
Labels: dev, CRUD

#53 Schemas/reports
  backend/app/mongo/schemas/reports.py
  history.md
Labels: documentation, dev

#54 Schemas/comments
  backend/app/mongo/schemas/comments.py
  history.md
Labels: documentation, dev

#55 Fix/models
  backend/app/mongo/models/comments.py
  backend/app/mongo/models/posts.py
  backend/app/mongo/models/users.py
  history.md
Labels: documentation

#59 Auth/verify guard and auth validation
  backend/app/api/deps.py
  backend/app/api/v1/api.py
  backend/app/api/v1/endpoints/auth.py
  backend/app/core/config.py
  backend/app/crud/crud_comments.py
  backend/app/crud/crud_likes.py
  backend/app/crud/crud_posts.py
  backend/app/crud/crud_reports.py
  backend/app/crud/crud_users.py
  backend/app/mongo/init_db.py
  backend/app/mongo/models/users.py
  backend/app/mongo/schemas/users.py
  backend/app/utils.py
  history.md
Labels: dev

#60 Routes/all in one -> Reports, Likes, Comments, Users, Auth
  backend/app/api/deps.py
  backend/app/api/v1/endpoints/auth.py
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/likes.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
  backend/app/crud/crud_comments.py
  backend/app/crud/crud_likes.py
  backend/app/crud/crud_reports.py
  backend/app/crud/crud_users.py
  backend/app/mongo/models/comments.py
  backend/app/mongo/models/likes.py
  backend/app/mongo/models/reports.py
  backend/app/mongo/models/users.py
  backend/app/mongo/schemas/comments.py
  backend/app/mongo/schemas/likes.py
  backend/app/mongo/schemas/reports.py
  backend/app/mongo/schemas/users.py
  backend/app/utils.py
  history.md
Labels: dev, CRUD

#67 Endpoints/statusmodel
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/likes.py
  backend/app/api/v1/endpoints/posts.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/api/v1/endpoints/users.py
  history.md
Labels: documentation, dev

#69 Crud/crud posts api
  backend/app/api/v1/endpoints/posts.py
  backend/app/api/v1/endpoints/users.py
  backend/app/crud/crud_posts.py
  backend/app/mongo/schemas/posts.py
  history.md
Labels: dev, CRUD

#74 Docstring/utils
  backend/app/utils.py
  history.md
Labels: dev, CRUD

#76 Docstring/misc
  backend/app/api/deps.py
  backend/app/api/v1/endpoints/auth.py
  backend/app/api/v1/endpoints/comments.py
  backend/app/api/v1/endpoints/reports.py
  backend/app/core/config.py
  backend/app/core/security.py
  backend/app/crud/crud_comments.py
  backend/app/crud/crud_reports.py
  backend/app/mongo/init_db.py
  backend/app/mongo/schemas/token.py
  backend/app/uvicorn_pre_start.py
  history.md
Labels: dev, CRUD

#75 added docstring to endpoints/user
  backend/app/api/v1/endpoints/users.py
  history.md
Labels: documentation, dev

#79 Docstring/likes fix
  backend/app/api/v1/endpoints/likes.py
  history.md
Labels: documentation, dev

#77 Added history for v0.4.7
  backend/app/main.py
  history.md
Labels: dev

#80 Class/models added plain models without pydantic
  backend/app/mongo/models/comments.py
  backend/app/mongo/models/likes.py
  backend/app/mongo/models/posts.py
  backend/app/mongo/models/reports.py
  backend/app/mongo/models/users.py
  history.md
Labels: documentation, dev
